apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ekd8e2sl1-dotnet-basic
  janus-idp.io/tekton: ekd8e2sl1-dotnet-basic
  backstage.io/kubernetes-id: ekd8e2sl1-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ekd8e2sl1-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
