apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ekd8e2sl1-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ekd8e2sl1-dotnet-basic-gitops